# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Rules of the Internet
email: moraes.maximiliano@gmail.com
description: 'The Rules of the Internet. Never NEVER forget rule #20!'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moraesmax.github.io/rules-of-the-internet" # the base hostname & protocol for your site
facebook_username: moraesmax
github_username:  moraesmax

# Build settings
markdown: kramdown
